//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class ConnConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConnConfig defaultInstance = ((ConnConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConnConfig())));
        
        public static ConnConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Uid=root;Database=duelsys_db; port=3307; Pwd=")]
        public string ConnDev {
            get {
                return ((string)(this["ConnDev"]));
            }
            set {
                this["ConnDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=studmysql01.fhict.local;Uid=dbi495554;Database=dbi495554;Pwd=Nechushtan!99" +
            "8;")]
        public string ConnProd {
            get {
                return ((string)(this["ConnProd"]));
            }
            set {
                this["ConnProd"] = value;
            }
        }
    }
}
